name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_STAGING: ${{ secrets.HEROKU_APP_STAGING }}
      HEROKU_APP_PROD: ${{ secrets.HEROKU_APP_PROD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Deploy to Heroku (Staging)
        run: |
          git remote add react-surveyor-staging https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_STAGING.git
          git push -f react-surveyor-staging origin/develop:refs/heads/master

      - name: Deploy to Heroku (Prod)
        if: github.ref == 'refs/heads/master'
        run: |
          git remote add react-surveyor https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_PROD.git
          git push -f react-surveyor origin/master:refs/heads/master
