name: Deploy

on: push

jobs:
  deploy:
    name: Deploy
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_STAGING: ${{ secrets.HEROKU_APP_STAGING }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deploy to Heroku
        run: |
          git remote add staging https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_STAGING.git
          git push -f staging origin/chore/task-4-setup-cd:refs/heads/master
