name: Test

on: push

jobs:
  test:
    name: Test
    env:
      REACT_APP_NIMBLE_SURVEY_BASE_URL: ${{ secrets.REACT_APP_NIMBLE_SURVEY_BASE_URL }}
      REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
      REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
      CYPRESS_VALID_EMAIL: ${{ secrets.CYPRESS_VALID_EMAIL }}
      CYPRESS_VALID_PASSWORD: ${{ secrets.CYPRESS_VALID_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install node packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Stylelint
        run: npm run stylelint

      - name: Unit test
        run: npm run test

      - name: UI test
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: http://localhost:3000
