name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install node packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Stylelint
        run: npm run stylelint

      - name: Unit test
        run: npm run test

      - name: UI test
        run: npm run cypress:run
